# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmd < Formula
  desc "Tool to cache slow commands."
  homepage "https://simse.io/ccmd"
  version "0.0.2-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simse/ccmd/releases/download/v0.0.2-alpha/ccmd_Darwin_x86_64.tar.gz"
      sha256 "f6fcfbdbf8af6d09dcbc1fe119a7ed0b52f22e4c2b915b583a57e8c2e1be3748"

      def install
        bin.install "ccmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simse/ccmd/releases/download/v0.0.2-alpha/ccmd_Darwin_arm64.tar.gz"
      sha256 "33a710bb48d8c536aedfd23de31ebcdb2ba51e1bdc04a41a9c1a829a61604076"

      def install
        bin.install "ccmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/simse/ccmd/releases/download/v0.0.2-alpha/ccmd_Linux_x86_64.tar.gz"
      sha256 "9a2a27f67042d4c59bee8f37029cf7338738f1453f829a65b854ca446fa4f55c"
      def install
        bin.install "ccmd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/simse/ccmd/releases/download/v0.0.2-alpha/ccmd_Linux_arm64.tar.gz"
      sha256 "ed68e3ef104e3c6bb42e25232152e245e5378c4dc5e68e2d8b1c8fb9532b3f70"
      def install
        bin.install "ccmd"
      end
    end
  end
end
