# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmd < Formula
  desc "Tool to cache slow commands."
  homepage "https://simse.io/ccmd"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simse/ccmd/releases/download/v0.0.5/ccmd_Darwin_x86_64.tar.gz"
      sha256 "cc0eb0fe541c023ee364ff7650dc3374268ea4d762dc90b8ec8856b25420912d"

      def install
        bin.install "ccmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simse/ccmd/releases/download/v0.0.5/ccmd_Darwin_arm64.tar.gz"
      sha256 "875eadcf3dc68517d3c56417140241f9d2c8250c19e6db7b70bb13bdfc8b48d0"

      def install
        bin.install "ccmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/simse/ccmd/releases/download/v0.0.5/ccmd_Linux_x86_64.tar.gz"
      sha256 "6b56a7e82bd72aa43bffd60acc6edab6be2b9e6372011ef801ff93d47370bcd4"
      def install
        bin.install "ccmd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/simse/ccmd/releases/download/v0.0.5/ccmd_Linux_arm64.tar.gz"
      sha256 "4bf19028f1faf3b2a84ef00d38fff9e79b5147df573daf0c47ec98620ec3e45f"
      def install
        bin.install "ccmd"
      end
    end
  end
end
